integrations:
  node_exporter:
    enabled: true
    # disable unused collectors
    disable_collectors:
      - ipvs #high cardinality on kubelet
      - btrfs
      - infiniband
      - xfs
      - zfs
    # exclude dynamic interfaces
    netclass_ignored_devices: "^(veth.*|cali.*|[a-f0-9]{15})$"
    netdev_device_exclude: "^(veth.*|cali.*|[a-f0-9]{15})$"
    # disable tmpfs
    filesystem_fs_types_exclude: "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|tmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"
    # drop extensive scrape statistics
    metric_relabel_configs:
    - action: drop
      regex: node_scrape_collector_.+
      source_labels: [__name__]
    relabel_configs:
    - replacement: TST-SMC-MINIO-VM01
      target_label: instance
  agent:
    enabled: true
    relabel_configs:
    - action: replace
      source_labels:
      - agent_hostname
      target_label: instance
    - action: replace
      target_label: job
      replacement: "integrations/agent-check"
    metric_relabel_configs:
    - action: keep
      regex: (prometheus_target_.*|prometheus_sd_discovered_targets|agent_build.*|agent_wal_samples_appended_total|process_start_time_seconds)
      source_labels:
      - __name__
  prometheus_remote_write:
  - basic_auth:
      password: glc_eyJvIjoiNzU5OTY0IiwibiI6ImludC1zbWwiLCJrIjoiUWtIZkg2YXNmMDI4NW1yaTc2OXEzN0dkIiwibSI6eyJyIjoidXMtYXp1cmUifX0=
      username: 690077
    url: https://prometheus-us-central2.grafana.net/api/prom/push
logs:
  configs:
  - clients:
    - basic_auth:
        password: glc_eyJvIjoiNzU5OTY0IiwibiI6ImludC1zbWwiLCJrIjoiUWtIZkg2YXNmMDI4NW1yaTc2OXEzN0dkIiwibSI6eyJyIjoidXMtYXp1cmUifX0=
        username: 344009
      url: https://logs-prod-us-central2.grafana.net/loki/api/v1/push
    name: integrations
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
metrics:
  configs:
  - name: integrations
    remote_write:
    - basic_auth:
        password: glc_eyJvIjoiNzU5OTY0IiwibiI6ImludC1zbWwiLCJrIjoiUWtIZkg2YXNmMDI4NW1yaTc2OXEzN0dkIiwibSI6eyJyIjoidXMtYXp1cmUifX0=
        username: 690077
      url: https://prometheus-us-central2.grafana.net/api/prom/push
    scrape_configs:
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal

